name: brown
favicon: null
layout_spectrum: 0.7687086870428175
typography_spectrum: 0.8610909904818982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5557167155202478
  lightness: 0.685287730069831
  saturation: 0.8860751022584736
  rhythmicContrast: 0.897598481271416
purpose: []
